# Site settings
title: Farshid Pirahansiah
author: Farshid Pirahansiah
url: https://pirahansiah.com
baseurl: ""
description: Computer Vision & AI Engineer

# Jekyll settings
markdown: kramdown
permalink: pretty
kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  - scope:
      path: "notes"
    values:
      layout: farshid_default

# Plugins
plugins:
  - jekyll-feed

include:
  - notes

# Exclude
exclude:
  - README.md
  - run.sh
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .git/
  - .gitignore
  - CNAME
  - scripts/
