/* generated by gen_front_matter.py — legacy /notes/... URLs -> page routes. */
(function(){ var P = window.PERMALINKS = window.PERMALINKS || {};
  var A = {

  };
  for (var k in A) if (!(k in P)) P[k] = A[k];
})();
