#!/usr/bin/env python3
"""Generate assets/js/search-index.js from content/*.md for client-side search.
Run: python3 scripts/gen_search_index.py
Output: window.SEARCH_INDEX = [ {slug, title, text, tags, url}, ... ]"""
import os, re, json

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
CONTENT = os.path.join(ROOT, 'content')

def slug_title(title):
    s = title.lower()
    s = re.sub(r'[^a-z0-9]+', '-', s).strip('-')
    return s

def clean(text):
    # remove markdown syntax for searchable text
    text = re.sub(r'```.*?```', ' ', text, flags=re.S)
    text = re.sub(r'\[([^\]]*)\]\([^)]*\)', r'\1', text)
    text = re.sub(r'[#*_`>|]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

entries = []
for fn in sorted(os.listdir(CONTENT)):
    if not fn.endswith('.md'): continue
    slug = fn[:-3]
    body = open(os.path.join(CONTENT, fn), encoding='utf-8').read()
    h1 = re.search(r'^#\s+(.+)$', body, re.M)
    title = ' '.join(h1.group(1).split()) if h1 else slug
    text = clean(body)
    # tags: headings + highlighted words
    tags = re.findall(r'^#{2,3}\s+(.+)$', body, re.M)
    tags = [' '.join(t.split()) for t in tags][:6]
    entries.append({
        'slug': slug,
        'title': title,
        'text': text[:1500],
        'tags': tags,
        'url': '/index.html#content/'+slug
    })

# add atlas + qr + swarm permanent pages
entries.append({'slug':'atlas','title':'Atlas — index of everything','text':'the single index of all publications courses notes slides projects connect','tags':['index','publications','courses','notes'],'url':'/index.html#atlas'})
entries.append({'slug':'qr','title':'Scan & Share — QR links','text':'qr codes referrals social profiles crypto addresses all links scan share','tags':['qr','links','social','crypto'],'url':'/qr'})
entries.append({'slug':'search','title':'Search','text':'search the entire knowledge base','tags':['search'],'url':'/search'})

js = '/* generated by scripts/gen_search_index.py */\nwindow.SEARCH_INDEX='+json.dumps(entries, ensure_ascii=False)+';'
out = os.path.join(ROOT, 'assets', 'js', 'search-index.js')
open(out, 'w', encoding='utf-8').write(js)
print('wrote', out, len(entries), 'entries')