#!/usr/bin/env python3
"""Generate assets/js/search-index.js from content/*.md for client-side search.
Run: python3 scripts/gen_search_index.py
Output: window.SEARCH_INDEX = [ {slug, title, text, tags, url}, ... ]"""
import os, re, json

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
PAGE_DIRS = ['content', 'expert-coaching-resources']
CONTENT = os.path.join(ROOT, 'content')


def page_files():
    for d in PAGE_DIRS:
        full = os.path.join(ROOT, d)
        if not os.path.isdir(full):
            continue
        for f in sorted(os.listdir(full)):
            if f.endswith('.md'):
                yield d, f

def slug_title(title):
    s = title.lower()
    s = re.sub(r'[^a-z0-9]+', '-', s).strip('-')
    return s

def strip_front_matter(text):
    m = re.match(r'^---\s*\n.*?\n---\s*\n', text, re.S)
    return text[m.end():] if m else text


def clean(text):
    # remove markdown syntax for searchable text
    text = re.sub(r'```.*?```', ' ', text, flags=re.S)
    text = re.sub(r'\[([^\]]*)\]\([^)]*\)', r'\1', text)
    text = re.sub(r'[#*_`>|]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

entries = []
for folder, fn in page_files():
    slug = fn[:-3]
    body = open(os.path.join(ROOT, folder, fn), encoding='utf-8').read()
    h1 = re.search(r'^#\s+(.+)$', body, re.M)
    title = ' '.join(h1.group(1).split()) if h1 else slug
    text = clean(strip_front_matter(body))   # the page header is metadata, not searchable text
    # tags: headings + highlighted words
    tags = re.findall(r'^#{2,3}\s+(.+)$', body, re.M)
    tags = [' '.join(t.split()) for t in tags][:6]
    entries.append({
        'slug': slug,
        'title': title,
        'text': text[:1500],
        'tags': tags,
        # the app route: '#content/<page>', and for a page in another folder its path
        'url': '/farshid/content/index.html#content/' + (slug if folder == 'content' else folder + '/' + slug)
    })

# add atlas + qr + swarm permanent pages
entries.append({'slug':'atlas','title':'Atlas — index of everything','text':'the single index of all publications courses notes slides projects connect','tags':['index','publications','courses','notes'],'url':'/farshid/content/index.html#atlas'})
entries.append({'slug':'qr','title':'Scan & Share — QR links','text':'qr codes referrals social profiles crypto addresses all links scan share','tags':['qr','links','social','crypto'],'url':'/farshid/content/index.html#content/qr'})
entries.append({'slug':'search','title':'Search Swarm','text':'search the entire knowledge base swarm search agents','tags':['search','swarm'],'url':'/farshid/content/swarm.html'})

# presentations / slide decks (live under content/, renamed to presentation-*)
SLIDES = [
  {'slug':'presentation-research-tools','title':'The New Era of Research Tools','tags':['presentation','research','agents'],'text':'research tools presentation autonomous research workflows agent swarms second brain obsidian citation finders peer review'},
  {'slug':'presentation','title':'Hermes Agent for Research Assistance','tags':['presentation','hermes-agent','research','arxiv'],'text':'hermes agent presentation research assistance academic engineering workflow automation arxiv integration multi agent execution'},
  {'slug':'presentation-cv','title':'Hermes Agent for Big Computer Vision Projects','tags':['presentation','hermes-agent','computer-vision'],'text':'hermes agent computer vision presentation big projects image processing deployment pipeline'},
  {'slug':'presentation-updates','title':'Hermes Agent — Recent Updates & Complete Feature Guide','tags':['presentation','hermes-agent','updates'],'text':'hermes agent recent updates features guide presentation full feature guide'},
  {'slug':'presentation-llm-optimization','title':'New LLM Optimization Methods — Run Local & Fast','tags':['presentation','llm','optimization','local'],'text':'llm optimization methods run local fast presentation on device models quantization'},
]
for s in SLIDES:
    entries.append({'slug':'notes-slides-'+s['slug'],'title':s['title'],'text':s['text'],'tags':s['tags'],'url':'/farshid/content/'+s['slug']+'.md'})

js = '/* generated by scripts/gen_search_index.py */\nwindow.SEARCH_INDEX='+json.dumps(entries, ensure_ascii=False)+';'
out = os.path.join(ROOT, 'search-index.js')  # engine files live at farshid/ root (assets/ removed)
open(out, 'w', encoding='utf-8').write(js)
print('wrote', out, len(entries), 'entries')